<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.0" />
	</ItemGroup>

</Project>
